# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 02:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 21, 2, 3, 20, 149533, tzinfo=utc), verbose_name='date published'),
        ),
    ]
